### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by casperdcl** [jdtournier/OOP_tutorial#1]
https://github.com/jdtournier/OOP_tutorial/blob/b179e1724f3a841fbaa072f8779176bff02b688a/build#L201

this can cause an infinite loop if two headers include each other

**Comment by jdtournier** [comment]
Darn edge cases... I'll take a look when I have a minute.

**Comment by casperdcl** [comment]
I just wrote a cmake script to do the same as this. 125 lines. might open source it if it proves cross-platform and bug-free

**Comment by casperdcl** [comment]
I didn't actually run this tbh but it prob is a bug
